export const ADD_SUPPORTER = 'ADD_SUPPORTER'
export const FETCH_SUPPORTERS_REQUEST = 'FETCH_SUPPORTERS_REQUEST'
export const FETCH_SUPPORTERS_SUCCESS = 'FETCH_SUPPORTERS_SUCCESS'
export const FETCH_SUPPORTERS_FAILURE = 'FETCH_SUPPORTERS_FAILURE'